
services:
  postgres:
    image: postgres:16
    container_name: spacehub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: spacehub_db
      POSTGRES_USER: spacehub_user
      POSTGRES_PASSWORD: spacehub_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: spacehub-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@spacehub.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build: ./backend
    container_name: spacehub-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spacehub_db
      SPRING_DATASOURCE_USERNAME: spacehub_user
      SPRING_DATASOURCE_PASSWORD: spacehub_password
      APPLICATION_CLOUDINARY_URL: cloudinary://123456789012345:ABCDE12345-FGHIJ67890KLMNO@dmh1v2p3z
      SPRING_MAIL_HOST: localhost
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME: ""
      SPRING_MAIL_PASSWORD: ""
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: spacehub-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: